/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserStateEnum = "ACTIVE" | "BLOCKED" | "VERIFICATION_PENDING";

export interface EmailVerification {
  attempts: Generated<number>;
  code_hash: string;
  email: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  user_id: string;
  verified: Generated<boolean | null>;
}

export interface RefreshToken {
  expires_at: Timestamp;
  id: Generated<string>;
  refresh_token_hash: string;
  user_id: string;
}

export interface Users {
  email: string;
  id: Generated<string>;
  name: string;
  password_hash: string;
  state: Generated<UserStateEnum>;
}

export interface DB {
  email_verification: EmailVerification;
  refresh_token: RefreshToken;
  users: Users;
}
